name: Build Release Windows

on:
  release:
    types: [ published ]

jobs:
  build-release:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller==5.8.0

      - name: Build with PyInstaller
        id: build
        run: |
          ./build-action

      - name: Create Release
        uses: Shopify/upload-to-release@v2.0.0
        with:
          name: MDCx-windows-x86_64.exe
          path: dist/MDCx-windows-x86_64.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}
